bls:
# python calculate_bls.py ../../infiles/UTR_Sequences_sample.txt ../../conservation_outfiles/sample_output.txt
	python calculate_bls.py ../../infiles/tiny_utrs.txt ../../conservation_outfiles/tiny_output.txt