bls:
	# python calculate_bls.py ../../infiles/UTR_Sequences_sample.txt ../../conservation_outfiles/sample_output2.txt
	# python calculate_bls.py ../../infiles/tiny_utrs.txt ../../conservation_outfiles/tiny_output2.txt
	python calculate_bls.py ../../infiles/UTR_Sequences_Ensembl_forTS_kathy_no_header.txt ../../conservation_outfiles/big_output.txt